#define MAX_SEGMENT_SIZE 64
#define HEADER_SIZE 6
#define PAYLOAD_SIZE (MAX_SEGMENT_SIZE - HEADER_SIZE - 1)
#define OVERHEAD_SIZE 3
#define LENGTH_BYTE_OFFSET 4
#define ACK_LENGTH 6

/* API Commands */
#define RESET 0x01
#define ALOHA_DISABLE 0x00
#define ALOHA_ENABLE 0x01
#define MODE 0x02
#define SET_ADDRESS 0x08
#define SET_SLOT_TIME 0x40
#define SET_BACKOFF_LIMIT 0x20
#define SET_MAX_TRANS 0x80
#define TRANSMIT 0x10

#define STATUS_NON_INIT 0x0
#define STATUS_IDLE 0x04
#define STATUS_RADIO_READY 0x01
#define STATUS_USER_READY 0x02
#define STATUS_WATING_ACK 0x10

#define SET_STATUS_NON_INIT(x) (x|=STATUS_NON_INIT)
#define SET_STATUS_IDLE(x) (x|=STATUS_IDLE)
#define SET_STATUS_RADIO_READY(x) (x|=STATUS_RADIO_READY)
#define SET_STATUS_USER_READY(x) (x|=STATUS_USER_READY)
#define SET_STATUS_WATING_ACK(x) (x|=STATUS_WATING_ACK)

#define UNSET_STATUS_NON_INIT(x) (x&= ~STATUS_NON_INIT)
#define UNSET_STATUS_IDLE(x) (x&= ~STATUS_IDLE)
#define UNSET_STATUS_RADIO_READY(x) (x&= ~STATUS_RADIO_READY)
#define UNSET_STATUS_USER_READY(x) (x&= ~STATUS_USER_READY)
#define UNSET_STATUS_WATING_ACK(x) (x&= ~STATUS_WATING_ACK)

#define IS_STATUS_NON_INIT(x) (x&STATUS_NON_INIT)
#define IS_STATUS_IDLE(x) (x&STATUS_IDLE)
#define IS_STATUS_RADIO_READY(x) (x&STATUS_RADIO_READY)
#define IS_STATUS_USER_READY(x) (x&STATUS_USER_READY)
#define IS_STATUS_WATING_ACK(x) (x&STATUS_WATING_ACK)

#define BAUDRATE B115200
